# Copyright 2023 EPAM Systems
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - id: Update Reportportal Password
    name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |

        gcloud container clusters get-credentials \
          $_CLUSTER --project $_PROJECT_ID --region $_REGION

        kubectl -n $_NAMESPACE port-forward svc/postgresql 5432:5432 &
        
        export DEBCONF_NOWARNINGS=yes
        apt-get update -yqq > /dev/null
        apt-get install net-tools postgresql-client -yqq > /dev/null

        export PGPASSWORD=$(kubectl get secret --namespace $_SERVICE_NAME \
                postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)

        HASH=$(echo -n $_HASH | base64 --decode)

        psql --host=$_HOST --user=$_DB_USER --dbname=$_SERVICE_NAME \
          --command="UPDATE users SET password = '$$HASH' WHERE login = '$_USER';"

        unset PGPASSWORD
    entrypoint: bash

substitutions:
  _HOST: ''
  _USER: ''
  _HASH: ''
  _REGION: ''
  _DB_USER: ''
  _CLUSTER: ''
  _NAMESPACE: ''
  _PROJECT_ID: ''
  _LOGS_BUCKET: ''
  _SERVICE_NAME: ''
  _SERVICE_ACCOUNT : ''

options:
  logging: GCS_ONLY
logsBucket: gs://$_LOGS_BUCKET

serviceAccount: projects/$_PROJECT_ID/serviceAccounts/$_SERVICE_ACCOUNT
